kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment
  namespace: appns
  labels:
    name: app-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-node

  template:
     metadata:
      labels:
        app: app-node
     spec:
      containers:
      - name: app-node-cont
        image: gokarni/docker-k8s:latest
        ports:
        - containerPort: 3000
        resources:
          requests: 
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 256Mi




