kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-vol
  namespace: nginxnamespace
  labels:
    app: local-pv
spec:
  accessModes: 
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
  

